<?php
/**
 * Enqueue the admin JavaScript and CSS assets.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

add_action( 'admin_enqueue_scripts', 'marcellus_social_profile_links_enqueue_admin_assets' );

function marcellus_social_profile_links_enqueue_admin_assets( $hook ) {
    // Only load on our specific admin page
    $allowed_pages = array(
        'toplevel_page_marcellus-social-profile-links-settings',
        //'marcellus-social-profile-links_page_other-settings-page'
    );

    if ( ! in_array( $hook, $allowed_pages, true ) ) {
        return;
    }

    // Load Core WordPress Media Library (JS/CSS)
    wp_enqueue_media();

    // Load Core WordPress Component Styles (Required for TabPanel/Flex/Panels)
    wp_enqueue_style( 'wp-components' );

    // Correctly target the plugin root directory from inside the includes folder
    $plugin_root_path = dirname( plugin_dir_path( __FILE__ ), 2 ) . '/';
    $plugin_root_url  = dirname( plugins_url( '', __FILE__ ), 2 ) . '/';

    // Path to the auto-generated asset file from @wordpress/scripts
    $asset_path = $plugin_root_path . 'build/marcellus-social-profile-links-admin/index.asset.php';
    
    if ( file_exists( $asset_path ) ) {
        $assets = include $asset_path;

        // Enqueue your compiled React App
        wp_enqueue_script(
            'marcellus-social-profile-links-admin-script', 
            $plugin_root_url . 'build/marcellus-social-profile-links-admin/index.js',
            $assets['dependencies'], 
            $assets['version'],
            true 
        );

        // Enqueue your compiled CSS generated by @wordpress/scripts
        $css_path = $plugin_root_path . 'build/marcellus-social-profile-links-admin/index.css';
        if ( file_exists( $css_path ) ) {
            wp_enqueue_style(
                'marcellus-social-profile-links-admin-styles',
                $plugin_root_url . 'build/marcellus-social-profile-links-admin/index.css',
                array(),
                $assets['version']
            );
        }
    }
}
